default: &default
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  database: cache
  <<: *default

test:
  database: cache
  <<: *default

production:
  database: cache
  <<: *default
